### ISSUE TITLE
Update feature to use new validity pattern

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-checkbox#68]
## Is your feature request related to a problem? Please describe.

The auro-checkbox element requires an update to meet new validation and error experiences. 

## Describe the solution you'd like

Update auro-select to use the new validity pattern as set by auro-input, combobox, etc... 

## Exit criteria 

This issue will be considered complete once the user and code experience matches the newly set validity pattern and the element API behaves in the same way.

**Comment by leeejune** [comment]
## Error state design changes
Form label (heading): stay as `auro-color-text-primary-on-light` instead of changing to `auro-color-text-error-on-light`
Helper text: size should be SMALL body text size, color remain as red
Label (text next to button): stay as `auro-color-text-primary-on-light` instead of changing to `auro-color-text-error-on-light`
Spacing between last form element and helper text: `auro-size-200`

![Screen Shot 2022-11-22 at 4 28 23 PM](https://user-images.githubusercontent.com/55998746/203447615-902527bc-3e4e-4817-bdef-043ada0e0aee.png)

@jason-capsule42
