### ISSUE TITLE
Update to use semantic-release-action v3

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-checkbox#90]
## Describe the bug

This component is currently using semantic-release-action v2, which is causing the most recent release to fail.

## To Reproduce
1. Go to https://github.com/AlaskaAirlines/auro-checkbox/actions
2. Look for "Test and publish #134"

## Expected behavior

PRs and their changes are released.

**Comment by blackfalcon** [comment]
UPDATE: This is not an issue with semantic release or the installed npm version. This is an issue with the legacy versions of Github Actions that no longer work due to Github no longer supporting Node 12 actions. This includes; 

1. actions/checkout
2. actions/setup-node
3. and... cycjimmy/semantic-release-action
